### ISSUE TITLE
GETing /v1/buckets raises a 500

### ISSUE THREAD

**Issue by magopian** [mozilla-services/kinto#114] opened 2015-07-05 12:35 UTC
```
2015-07-05 14:28:16,402 ERROR [venusian][Dummy-5] "GET   /v1/buckets" ? (? ms) 'None:read' lang=None; exception=Traceback (most recent call last):
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/router.py", line 145, in handle_request
    view_name
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/view.py", line 527, in _call_view
    response = view_callable(context, request)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 601, in __call__
    return view(context, request)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 327, in attr_view
    return view(context, request)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 303, in predicate_wrapper
    return view(context, request)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 241, in _secured_view
    result = _permitted(context, request)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 239, in _permitted
    permission)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/cliquet/authorization.py", line 46, in permits
    get_bound_permissions=self.get_bound_permissions)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/cliquet/permission/__init__.py", line 112, in check_permission
    object_id, permission, get_bound_permissions)
  File "/Users/mathieu/.virtualenvs/kinto/lib/python2.7/site-packages/cliquet/permission/memory.py", line 78, in object_permission_authorized_principals
    keys = get_bound_permissions(object_id, permission)
  File "/Users/mathieu/kinto/kinto/authorization.py", line 146, in get_bound_permissions
    return build_permissions_set(*args, **kwargs)
  File "/Users/mathieu/kinto/kinto/authorization.py", line 129, in build_permissions_set
    for obj, permission_list in inheritance_tree[bound_permission].items():
KeyError: 'None:read'; uid=10ea4e5fbf849196a4fe8a9c250b737dd5ef17abbeb8f99692d62828465a9823; errno=None; agent=HTTPie/0.8.0; authn_type=BasicAuth
```

**Comment by leplatrem** [comment] 2015-07-06 08:20
Duplicate of #88

**Closed by leplatrem** 2015-07-06 08:20 UTC
